[package]
name = "py-spy"
version = "0.1.1"
authors = ["Ben Frederickson <github@benfrederickson.com>"]
repository = "https://github.com/benfred/py-spy"
readme = "README.md"
exclude = ["images/*"]

[dependencies]
clap = "2"
console = "0.6.1"
indicatif = "0.9.0"
env_logger = "0.5"
failure = "0.1.1"
goblin = "0.0.15"
lazy_static = "1.1.0"
libc = "0.2.34"
log = "0.4"
regex = "1"
tempdir = "0.3"
tempfile = "3.0.3"
read-process-memory = "0.1"
proc-maps = "0.1"

[target.'cfg(unix)'.dependencies]
termios = "0.2.2"

[target.'cfg(windows)'.dependencies]
winapi = {version = "0.3", features = ["winbase", "consoleapi", "wincon", "handleapi", "processenv" ]}

[patch.crates-io]
read-process-memory = {git = "https://github.com/benfred/read-process-memory.git"}
